//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookBaseEntities1 : DbContext
    {
        private static BookBaseEntities1 _context;
        public BookBaseEntities1()
            : base("name=BookBaseEntities1")
        {
        }

        public static BookBaseEntities1 GetContext()
        {
            if (_context == null)
                _context = new BookBaseEntities1();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autor> Autor { get; set; }
        public virtual DbSet<BookTest> BookTest { get; set; }
        public virtual DbSet<Predmet> Predmet { get; set; }
        public virtual DbSet<So_Autor> So_Autor { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
    }
}
