//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookTest
    {
        public int ID { get; set; }
        public string Name_Book { get; set; }
        public int Publishing_Year { get; set; }
        public string Place_of_publishing { get; set; }
        public string Publisher_Name { get; set; }
        public int ID_Autor { get; set; }
        public string Obrazov_Ychrezd { get; set; }
        public int ID_Teacher { get; set; }
        public int ID_Predmet { get; set; }
        public int ID_Student { get; set; }
        public string Text { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Predmet Predmet { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
